<?php

declare(strict_types=1);

namespace Hydra\Database\Contracts;

/**
 * The only way the framework talks to a database: a narrow, driver-agnostic
 * surface where every value travels as a bound parameter, so no caller is ever
 * handed a place to build SQL from a string.
 */
interface ConnectionInterface
{
    /**
     * @param array<string|int, scalar|null> $params bound values, named or positional
     * @return list<array<string, mixed>>
     */
    public function select(string $sql, array $params = []): array;

    /**
     * @param array<string|int, scalar|null> $params bound values, named or positional
     * @return array<string, mixed>|null
     */
    public function selectOne(string $sql, array $params = []): ?array;

    /**
     * Returns the affected row count.
     *
     * @param array<string|int, scalar|null> $params bound values, named or positional
     */
    public function execute(string $sql, array $params = []): int;

    /**
     * The id generated by the most recent INSERT on this connection. A string,
     * uncast, because UUID and other non-integer primary keys are legitimate and
     * an integer id can exceed PHP_INT_MAX; callers on integer keys cast at
     * their own call site.
     */
    public function lastInsertId(): string;

    /**
     * Run $fn inside a transaction and return its value, committing on a clean
     * return and rolling back on any throwable. Nested calls join the outermost
     * transaction rather than opening their own, so an inner success still rolls
     * back if the outer call later fails.
     */
    public function transaction(callable $fn): mixed;
}
