<?php

declare(strict_types=1);

namespace Hydra\Database\Contracts;

/**
 * Connection interface
 */
interface ConnectionInterface
{
    /**
     * Run a query and return every row as an associative array
     */
    public function select(string $sql, array $params = []): array;

    /**
     * Run a query and return the first row, or null if there are none
     */
    public function selectOne(string $sql, array $params = []): ?array;

    /**
     * Run a write (INSERT/UPDATE/DELETE) and return the affected row count
     */
    public function execute(string $sql, array $params = []): int;

    /**
     * The id generated by the most recent INSERT on this connection
     */
    public function lastInsertId(): string;

    /**
     * Run $fn inside a database transaction and return its value
     */
    public function transaction(callable $fn): mixed;
}
